name: CI workflow

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
  
  jobs:
    bbuild:
      runs-on: ubuntu-latest
      container:
        image: python:3.9-slim
  