name: CI workflow

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flaked
        run: |
          flaked service --count --select=E9,F63,F7,F02 --show-source --statistics
          flaked service --count --max-complexity=10 --max-line-length=127 --statics
      - name: Run unit test nose
        run: notetests -v --with-spec --spec-color --with-coverege --cover-package=app